=== Xanaks15/tecweb/actividades/a10/serviciovod.dtd
<!ELEMENT catalogovod (cuenta,contenido)>
<!ELEMENT cuenta (perfiles)>
<!ELEMENT perfiles (perfil)*>
<!ELEMENT perfil EMPTY>
<!ATTLIST perfil 
nombre CDATA #REQUIRED
idioma CDATA #REQUIRED
>
<!ATTLIST cuenta correo CDATA #REQUIRED>

<!ELEMENT contenido (peliculas,programas)>
<!ELEMENT peliculas (genero)+>
<!ATTLIST genero nombre CDATA #REQUIRED>
<!ELEMENT genero (titulo)*>
<!ELEMENT titulo (#PCDATA)>
<!ATTLIST titulo duracion CDATA #REQUIRED>

<!ELEMENT programas (genero)+>

=== Xanaks15/tecweb/actividades/a10/serviciod2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogovod SYSTEM "serviciovod.dtd">
<catalogovod>
    <cuenta correo="josue.torres@gmail.com">
        <perfiles> 
            <perfil nombre="Ana" idioma="Espaniol"/>
            <perfil nombre="Josue" idioma="Espaniol"/>
        </perfiles>
    </cuenta>
    <contenido>
        <peliculas>
            <genero nombre="Terror">
                <titulo duracion="125 minutos">Sonrie</titulo>
                <titulo duracion="150 minutos">El Callejon de las Almas Perdidas</titulo>
                <titulo duracion="110 minutos">El Faro</titulo>
                <titulo duracion="109 minutos">Psicosis</titulo>
            </genero>
            <genero nombre="Ciencia Ficcion">
                <titulo duracion="117 minutos">Alien - El Octavo Pasajero</titulo>
                <titulo duracion="117 minutos">Blade Runner</titulo>
                <titulo duracion="129 min minutos">2001: Odisea del Espacio</titulo>
                <titulo duracion="169 minutos">Interestelar</titulo>
            </genero>
        </peliculas>

        <programas>
            <genero nombre="Terror">
                <titulo duracion="177 capitulos">The Walking Dead</titulo>
                <titulo duracion="76 capitulos">La Hora Embrujada</titulo>
                <titulo duracion="9 capitulos">Marianne</titulo>
                <titulo duracion="10 capitulos">Territorio Lovecraft</titulo>
            </genero>
            <genero nombre="Drama">
                <titulo duracion="62 capitulos">Breaking Bad</titulo>
                <titulo duracion="73 capitulos">Juego de Tronos</titulo>
                <titulo duracion="19 capitulos">Black Mirror</titulo>
                <titulo duracion="26 capitulos">Dark</titulo>
            </genero>
        </programas>
    </contenido>
</catalogovod>
